# Generated by Django 4.1 on 2022-10-06 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ADD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastrar',
            options={'ordering': ('Nome',)},
        ),
        migrations.AddField(
            model_name='cadastrar',
            name='Bairro',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastrar',
            name='BI_No',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cadastrar',
            name='Id_Ca',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cadastrar',
            name='telef',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
